library(Hmisc)
library(ggplot2)
library(ggthemes) # visualization
library(Metrics)
library(dplyr)

extractFeaturesI <- function(data) {
  features <- c("Pclass",
                "Sex",
                "Age",
                "SibSp",
                "Parch",
                "Fare",
                "Cabin",
                "Embarked")
  fea <- data[,features]
  
  fea$Sex <- gsub('female', '0', fea$Sex)
  fea$Sex <- gsub('male', '1', fea$Sex)
  
  fea$Embarked[fea$Embarked=="S"] <- "1"
  fea$Embarked[fea$Embarked=="Q"] <- "2"
  fea$Embarked[fea$Embarked=="C"] <- "3"
  
  fea[substr(fea$Cabin,0,1)=="A", "Cabin"] <-"1"
  fea[substr(fea$Cabin,0,1)=="B", "Cabin"] <-"2"
  fea[substr(fea$Cabin,0,1)=="C", "Cabin"] <-"3"
  fea[substr(fea$Cabin,0,1)=="D", "Cabin"] <-"4"
  fea[substr(fea$Cabin,0,1)=="E", "Cabin"] <-"5"
  fea[substr(fea$Cabin,0,1)=="F", "Cabin"] <-"6"
  fea[substr(fea$Cabin,0,1)=="G", "Cabin"] <-"7"
  fea[substr(fea$Cabin,0,1)=="T", "Cabin"] <-"8"
  
  fea[] <- lapply(fea, function(x) as.numeric(as.character(x)))
  fea[!is.na(fea$Fare),'Fare']<-log(1+fea[!is.na(fea$Fare),'Fare'])
  fea[!is.na(fea$Age),'Age']<-log(1+fea[!is.na(fea$Age),'Age'])
  return(fea)
}
setwd("D:/ADP실기/KaggleR/titanic/")
train<-read.csv('train.csv',stringsAsFactors=FALSE)
ysurvived<-train$Survived
test<-read.csv('test.csv',stringsAsFactors=FALSE)
passengerids<-test$PassengerId
ytrain<-extractFeaturesI(train)
ytest<-extractFeaturesI(test)
y <- rbind(ytrain,ytest)                  
for(c in names(y))
{
  y[!is.na(y[,c]),c]<-scale(y[!is.na(y[,c]),c]) 
}

y[is.na(y)]<- -999

y[] <- round(y, digits = 6) 

ycomplex <-y[,]
ycomplex[] <- lapply(ycomplex, function(x) as.complex((x)))
ycomplex[ycomplex==complex(real = -999, imaginary = 0)] = complex(real = 0, imaginary = 1)

gpReal<-function(data)
{
  p<-(0.200000*tanh((((((11.71468257904052734)) - (((((data$Parch) * (((((data$Parch) * (ifelse(rep(1.,NROW(data))*(data$Cabin < -998),(11.71468257904052734),((data$SibSp) * (data$Cabin)))))) * (data$SibSp))))) * (data$SibSp))))) - ((((((14.90702819824218750)) * ((((data$Sex) + (cos((data$Age))))/2.0)))) * 2.0)))) +
        0.200000*tanh(((((((((((data$Fare) * 2.0)) - ((3.92554259300231934)))) - (((data$SibSp) + (((((data$Sex) * 2.0)) * 2.0)))))) * ((10.0)))) * ((((((data$Sex) * (data$Parch))) + ((((((((data$SibSp) * 2.0)) * 2.0)) + ((11.61296272277832031)))/2.0)))/2.0)))) +
        0.200000*tanh((((2.73733806610107422)) - (ifelse(rep(1.,NROW(data))*(((data$Cabin) * (((data$Pclass) * 2.0))) < -998),(13.47367191314697266),((((((((((((data$Sex) + (cos((data$Age))))) * 2.0)) * 2.0)) + (tanh((tanh((data$Age))))))) + (data$Pclass))) + (((sin((data$Age))) * 2.0))))))) +
        0.200000*tanh(ifelse(rep(1.,NROW(data))*(((data$Cabin) + (((((((((data$Pclass) + (data$Parch))) / 2.0)) - (data$Embarked))) + (data$Pclass)))) < -998),((data$Sex) * (data$Cabin)),((((((((data$Pclass) + (data$Pclass))) + (data$Pclass))) * (data$Cabin))) + ((10.41979503631591797))))) +
        0.200000*tanh(((((((data$Parch) * (data$Sex))) - (((sin((sin(((((((sin((ifelse(rep(1.,NROW(data))*(data$Age > -998),((data$Age) / 2.0),((data$Parch) * ((7.0))))))) + (sin((data$Sex))))/2.0)) * 2.0)))))) * ((7.0)))))) - (((data$SibSp) + (data$Pclass))))) +
        0.200000*tanh((((((((-1.0*((((cos((data$Embarked))) + (((ifelse(rep(1.,NROW(data))*(data$Pclass < -998),(10.70365810394287109),data$Sex)) + (data$Pclass)))))))) + (((sin((cos((data$Fare))))) - (cos((((data$Cabin) * (data$Embarked))))))))) * ((11.23421764373779297)))) * ((10.70365810394287109)))) +
        0.200000*tanh(((((((((((((((tanh((tanh((tanh((data$Cabin))))))) - (((((((data$Pclass) / 2.0)) * (data$SibSp))) + (((data$Sex) + (ifelse(rep(1.,NROW(data))*(data$Age < -998),data$Pclass,((data$Age) + (data$Pclass)))))))))) * 2.0)) * 2.0)) * 2.0)) * 2.0)) * 2.0)) * 2.0)) +
        0.200000*tanh((((9.0)) * ((((11.77857303619384766)) * (((((data$Fare) + (((((((((data$Fare) + (((((((data$Fare) + (((sin((data$Parch))) * 2.0)))) - (data$SibSp))) * 2.0)))) - (data$Parch))) + (data$Embarked))) * 2.0)))) + (sin((data$Parch))))))))) +
        0.200000*tanh(((data$Age) * ((((14.12567138671875000)) * (((data$Age) * (((((tanh((data$Sex))) - (((((data$Sex) - (tanh((ifelse(rep(1.,NROW(data))*(data$Age < -998),((data$Fare) - (data$SibSp)),(-1.0*((data$Age))))))))) * ((14.12567138671875000)))))) - (((data$SibSp) * 2.0)))))))))) +
        0.200000*tanh(((((data$Pclass) + ((-1.0*((cos((((cos((((data$Age) * 2.0)))) * (data$Sex)))))))))) * (((((((((((((((((data$Sex) - ((-1.0*((data$Pclass)))))) - ((-1.0*((data$Age)))))) * 2.0)) * 2.0)) - (data$Age))) * 2.0)) * 2.0)) * 2.0)))) +
        0.200000*tanh(((ifelse(rep(1.,NROW(data))*(((data$Pclass) * (((data$Cabin) * 2.0))) > -998),data$Pclass,cos((((((cos((data$Fare))) * (((((data$Cabin) / 2.0)) + (data$Sex))))) * (data$Pclass)))))) * (((((((((((((data$Sex) * 2.0)) * 2.0)) * 2.0)) * 2.0)) * 2.0)) * 2.0)))) +
        0.200000*tanh(ifelse(rep(1.,NROW(data))*(data$Age < -998),sin((((data$Embarked) * 2.0))),((((cos(((((((ifelse(rep(1.,NROW(data))*(data$Cabin < -998),((data$Embarked) / 2.0),((data$Cabin) / 2.0))) + (tanh((data$Fare))))/2.0)) * (data$Cabin))))) - (((((data$Pclass) / 2.0)) + (data$Age))))) - (data$SibSp)))) +
        0.200000*tanh(cos((((data$Age) * ((((ifelse(rep(1.,NROW(data))*(((data$Cabin) * (data$Parch)) > -998),(((sin((ifelse(rep(1.,NROW(data))*(data$Cabin > -998),sin(((((data$Fare) + (data$Age))/2.0))),((data$Fare) * 2.0))))) + (data$Age))/2.0),(((-1.0*((data$Cabin)))) * (data$Parch)))) + (data$Cabin))/2.0)))))) +
        0.200000*tanh(((sin((((((data$Sex) * (data$Embarked))) * 2.0)))) + ((((-1.0*((data$Parch)))) * (ifelse(rep(1.,NROW(data))*(data$Sex > -998),(((((((((data$SibSp) * ((-1.0*((data$SibSp)))))) + (((data$Embarked) * (data$Embarked))))/2.0)) + (data$Sex))) * (data$Age)),data$Embarked)))))) +
        0.200000*tanh(((((data$Sex) * (ifelse(rep(1.,NROW(data))*(((data$Age) + (data$Fare)) > -998),data$Pclass,((((((((data$Embarked) * (((data$SibSp) * 2.0)))) - (data$SibSp))) + (data$Parch))) + (data$Fare)))))) - (((sin(((((data$Age) + (data$SibSp))/2.0)))) * 2.0)))) +
        0.200000*tanh(((((((((sin((((((((tanh((data$Fare))) * (data$Cabin))) + (sin(((((((((data$Fare) * 2.0)) * 2.0)) + (data$Cabin))/2.0)))))) + (sin((((((((data$Fare) + (tanh((data$Fare))))/2.0)) + (data$Age))/2.0)))))))) * 2.0)) * 2.0)) * 2.0)) * 2.0)) +
        0.200000*tanh(((((((((((((((((sin((((cos((((data$Sex) + (((data$Sex) + (data$Parch))))))) - (((((data$Parch) - (cos((data$Fare))))) - (((data$Fare) * (data$Cabin))))))))) * 2.0)) * 2.0)) * 2.0)) * 2.0)) * 2.0)) * 2.0)) * 2.0)) * 2.0)) +
        0.200000*tanh((((((9.0)) * (sin(((((9.0)) * (tanh((((sin(((((9.0)) * ((((-1.0*(((9.0))))) * ((-1.0*((((data$Cabin) + (ifelse(rep(1.,NROW(data))*(data$Fare > -998),((data$Fare) - (data$Age)),data$Age))))))))))))) * 2.0)))))))))) / 2.0)) +
        0.200000*tanh(((data$Sex) * ((-1.0*((((((((((((((((((data$Sex) + (((((cos((data$Cabin))) + (((((data$Age) - (data$Sex))) - (sin((((((data$Age) * 2.0)) * 2.0)))))))) * 2.0)))) * 2.0)) * 2.0)) * 2.0)) * 2.0)) * 2.0)) * 2.0)) * 2.0))))))) +
        0.200000*tanh((((((9.0)) - ((((7.0)) * (data$Age))))) * ((((10.54393100738525391)) * ((((10.54393100738525391)) * (((sin((((((8.77409076690673828)) + (((ifelse(rep(1.,NROW(data))*(data$Fare < -998),data$Age,((data$SibSp) - ((((8.77409362792968750)) * (data$Fare)))))) * ((9.0)))))/2.0)))) * 2.0)))))))) +
        0.200000*tanh(((((((((((((((cos(((((((((11.13515090942382812)) + ((((((1.0)) - (((data$Embarked) - (((data$Fare) * 2.0)))))) * 2.0)))) * 2.0)) * 2.0)))) * 2.0)) * 2.0)) * 2.0)) * 2.0)) - (((data$Sex) * (((data$Fare) * 2.0)))))) - (data$Sex))) * 2.0)) +
        0.200000*tanh(((((((((sin(((((((tanh((ifelse(rep(1.,NROW(data))*(((sin((data$Age))) + (((sin((data$Embarked))) + (data$Cabin)))) < -998),data$Fare,((data$Embarked) - (data$SibSp)))))) * (((data$Cabin) - (data$Age))))) + (data$Embarked))/2.0)))) * 2.0)) * 2.0)) * 2.0)) * 2.0)) +
        0.200000*tanh((((12.75471496582031250)) * ((((((12.75471496582031250)) * 2.0)) * (sin((((data$Fare) * ((((12.75471496582031250)) - (sin((sin((ifelse(rep(1.,NROW(data))*(data$Fare > -998),ifelse(rep(1.,NROW(data))*(data$Embarked > -998),(((-1.0*((((data$Fare) * 2.0))))) * 2.0),data$Sex),(12.75471496582031250))))))))))))))))) +
        0.200000*tanh(((((data$Embarked) - (((sin((((((data$SibSp) + (data$Parch))) * 2.0)))) * 2.0)))) * (((ifelse(rep(1.,NROW(data))*(data$Age < -998),sin((((data$Parch) * 2.0))),((data$SibSp) * 2.0))) + (((data$Embarked) * (((sin((((data$SibSp) + (data$Parch))))) * 2.0)))))))) +
        0.200000*tanh(((((((data$Fare) * (((data$Sex) * (data$Pclass))))) - (ifelse(rep(1.,NROW(data))*(data$Age < -998),data$Sex,(((((data$Fare) + (data$Age))/2.0)) + (((((data$Fare) + (data$Pclass))) + (data$Pclass)))))))) - (sin((((data$Cabin) * (data$Age))))))) +
        0.200000*tanh(sin((((data$Cabin) * (ifelse(rep(1.,NROW(data))*(((data$Cabin) + (((data$Fare) * 2.0))) < -998),cos((((cos((((((7.0)) + (cos((cos((data$Pclass))))))/2.0)))) * (data$Fare)))),cos((((ifelse(rep(1.,NROW(data))*(data$Cabin > -998),data$Cabin,(7.0))) * (data$Fare)))))))))) +
        0.200000*tanh(sin((((data$Embarked) + (((((((((9.0)) * (data$Age))) + (ifelse(rep(1.,NROW(data))*(data$Cabin < -998),data$Fare,ifelse(rep(1.,NROW(data))*(data$Age < -998),data$Age,((data$Fare) + (data$Embarked))))))/2.0)) + (((cos((ifelse(rep(1.,NROW(data))*(data$Cabin < -998),data$Fare,data$Embarked)))) * (data$Cabin))))))))) +
        0.200000*tanh(((((((sin((((cos((((data$Fare) * ((((14.61405944824218750)) + (((((14.61406230926513672)) + (data$Pclass))/2.0)))))))) * ((14.61406612396240234)))))) * (((sin((data$Fare))) * ((((14.61406230926513672)) + ((((((data$Fare) / 2.0)) + ((14.61406612396240234)))/2.0)))))))) * 2.0)) * (data$Fare))) +
        0.200000*tanh(ifelse(rep(1.,NROW(data))*(((data$Age) * (data$Parch)) > -998),((((((sin(((-1.0*(((((data$Age) + (((cos(((((4.0)) * ((((3.0)) + (data$Age))))))) * (((((data$SibSp) * 2.0)) * 2.0)))))/2.0))))))) + (data$SibSp))) * 2.0)) * 2.0),data$Age)) +
        0.200000*tanh(((((((((((((((((cos((((data$Fare) * (((((((ifelse(rep(1.,NROW(data))*(data$Age > -998),((data$Age) * 2.0),tanh((((data$SibSp) * (data$Cabin)))))) * 2.0)) * (data$Cabin))) - (data$Sex))))))) * 2.0)) * 2.0)) * 2.0)) * 2.0)) * 2.0)) * 2.0)) * 2.0)) * 2.0)) +
        0.200000*tanh(((sin((((((data$Age) * (((data$Cabin) * ((2.65171122550964355)))))) * (((((((ifelse(rep(1.,NROW(data))*(((data$Cabin) * (data$Parch)) < -998),(2.65171122550964355),ifelse(rep(1.,NROW(data))*(((data$Cabin) * (data$Embarked)) < -998),data$Age,(3.0)))) * 2.0)) * (data$Parch))) * 2.0)))))) * 2.0)) +
        0.200000*tanh(((((data$Sex) * 2.0)) * ((-1.0*((cos(((((((((((((-1.0*((data$Parch)))) - ((-1.0*((((((ifelse(rep(1.,NROW(data))*(data$Age < -998),data$Pclass,(((7.0)) * 2.0))) * 2.0)) * 2.0))))))) * (data$Age))) - (data$Parch))) - (((data$Parch) * 2.0)))) / 2.0))))))))) +
        0.200000*tanh(((((ifelse(rep(1.,NROW(data))*(data$Age < -998),data$Parch,tanh((data$Age)))) * (((((tanh((tanh((data$Pclass))))) + (((data$Fare) * 2.0)))) * (((((data$Cabin) - (data$Age))) - (data$Sex))))))) * (((data$Age) - (tanh((tanh((data$Pclass))))))))) +
        0.200000*tanh(((((((((cos((((cos((((data$Fare) + (data$Cabin))))) + (((((ifelse(rep(1.,NROW(data))*(((data$Fare) * (((data$Fare) * (data$Cabin)))) < -998),(7.85861682891845703),(((((9.0)) + (data$Cabin))) * 2.0))) * (data$Fare))) * 2.0)))))) * 2.0)) * 2.0)) * 2.0)) * 2.0)) +
        0.200000*tanh(sin((((((((((data$Cabin) * ((6.79775619506835938)))) - (data$SibSp))) - (((data$Sex) - (tanh(((((((((data$Fare) * 2.0)) - (tanh((((data$Age) * 2.0)))))) + ((6.79775953292846680)))/2.0)))))))) * (((sin((data$Fare))) - (((data$Fare) * 2.0)))))))) +
        0.200000*tanh(((((data$Sex) * (((((((data$Embarked) + (data$SibSp))) * 2.0)) * 2.0)))) * (ifelse(rep(1.,NROW(data))*(data$Age < -998),data$Parch,((((((((((((((((((data$Age) - (data$SibSp))) * 2.0)) * 2.0)) * 2.0)) - (data$Sex))) * 2.0)) * 2.0)) * 2.0)) - (data$Embarked)))))) +
        0.200000*tanh(((((sin((((((cos((data$Embarked))) - (data$Age))) * ((((ifelse(rep(1.,NROW(data))*(data$Cabin < -998),((((cos((data$SibSp))) - (data$SibSp))) * 2.0),((data$Age) - (cos((data$Embarked)))))) + (data$Cabin))/2.0)))))) * ((14.78466892242431641)))) * ((14.78466892242431641)))) +
        0.200000*tanh(((((cos((((ifelse(rep(1.,NROW(data))*(ifelse(rep(1.,NROW(data))*(data$Age < -998),data$Cabin,data$Fare) > -998),(14.46325778961181641),data$Age)) * ((((((((data$Pclass) + ((((9.58765792846679688)) - (ifelse(rep(1.,NROW(data))*(data$Age < -998),data$Sex,(((data$Sex) + (data$Parch))/2.0))))))/2.0)) * (data$Fare))) / 2.0)))))) * 2.0)) * 2.0)) +
        0.200000*tanh((-1.0*((((data$Sex) * (((sin(((((-1.0*((ifelse(rep(1.,NROW(data))*(((data$Fare) + (data$Age)) > -998),data$Pclass,data$Fare))))) * (((data$Age) * ((((14.18832111358642578)) - ((((((data$Pclass) + ((((data$Age) + (data$Pclass))/2.0)))) + (data$Age))/2.0)))))))))) * 2.0))))))) +
        0.200000*tanh(((sin((((cos((((ifelse(rep(1.,NROW(data))*(((data$Age) * (data$Embarked)) < -998),data$Embarked,((data$Cabin) * ((13.33716201782226562))))) * (data$Fare))))) * (((tanh((data$Age))) * (((((-1.0*((data$Parch)))) + (((cos((data$Cabin))) * ((13.33716201782226562)))))/2.0)))))))) * 2.0)) +
        0.200000*tanh(((((((((((((sin((((((((((data$Cabin) * (data$Fare))) * (data$Fare))) + (((sin((tanh((tanh((data$SibSp))))))) * (ifelse(rep(1.,NROW(data))*(data$Cabin < -998),data$Embarked,tanh((data$Fare)))))))) * 2.0)))) * 2.0)) * 2.0)) * 2.0)) * 2.0)) * 2.0)) * 2.0)) +
        0.200000*tanh(((sin(((((((10.0)) * (((data$Cabin) * ((((data$Age) + (data$Fare))/2.0)))))) * (((data$Cabin) * (ifelse(rep(1.,NROW(data))*(data$Cabin > -998),data$Fare,(((data$Age) + (ifelse(rep(1.,NROW(data))*((((-1.0*((data$Fare)))) * (data$Cabin)) > -998),data$Fare,data$Cabin)))/2.0))))))))) * 2.0)) +
        0.200000*tanh(((((((sin((((data$Cabin) * (ifelse(rep(1.,NROW(data))*(((((((((data$Fare) + (data$Age))) * (data$Cabin))) - (data$Cabin))) * (data$Sex)) < -998),data$Fare,(((5.48772954940795898)) + (((((data$Fare) / 2.0)) + (data$Age)))))))))) * 2.0)) * 2.0)) * 2.0)) +
        0.200000*tanh(cos((ifelse(rep(1.,NROW(data))*(((data$Cabin) * (((data$Fare) + (data$Embarked)))) < -998),((((data$Age) * (data$Age))) * (data$Age)),((((((((data$Embarked) - (((((data$Cabin) * (data$Age))) * (data$Pclass))))) - (data$Cabin))) * (data$Cabin))) / 2.0))))) +
        0.200000*tanh(ifelse(rep(1.,NROW(data))*(data$Fare > -998),ifelse(rep(1.,NROW(data))*(data$Age > -998),(((((((-1.0*((data$Sex)))) / 2.0)) - (((data$SibSp) * (data$Pclass))))) - ((((((data$Pclass) * (data$Sex))) + (((((data$Fare) * 2.0)) * (data$Sex))))/2.0))),((data$Sex) * (data$Pclass))),data$Fare)) +
        0.200000*tanh(sin(((((((12.66003704071044922)) * ((((12.66003704071044922)) + (data$Embarked))))) * (((data$Age) - (sin((((sin((data$Pclass))) - (ifelse(rep(1.,NROW(data))*(data$Age < -998),ifelse(rep(1.,NROW(data))*(data$Age < -998),((sin((data$Cabin))) - (data$Pclass)),data$Embarked),((data$Sex) * 2.0))))))))))))) +
        0.200000*tanh(((((data$Sex) + (((data$Cabin) * (data$Cabin))))) * (sin(((((1.31758725643157959)) * (ifelse(rep(1.,NROW(data))*(data$Cabin > -998),data$SibSp,((data$Sex) + (((data$Sex) * (((cos((data$Cabin))) * (((((data$Cabin) * (data$Cabin))) * (data$Fare)))))))))))))))) +
        0.200000*tanh(((((((data$SibSp) - (ifelse(rep(1.,NROW(data))*(data$Age > -998),ifelse(rep(1.,NROW(data))*(data$Embarked > -998),data$Sex,data$Embarked),((((data$Fare) + (data$Embarked))) + (((data$Embarked) + (data$Sex)))))))) + (data$Parch))) * (((((data$Fare) + (data$Parch))) * ((-1.0*((data$Pclass)))))))) +
        0.200000*tanh(((((((cos((((cos((sin((tanh((((((data$Pclass) * (data$Embarked))) + (data$Fare))))))))) * (ifelse(rep(1.,NROW(data))*(data$Age < -998),ifelse(rep(1.,NROW(data))*(data$Cabin < -998),(((((data$Fare) * (data$Age))) + ((1.60368955135345459)))/2.0),data$Age),data$Cabin)))))) * 2.0)) * 2.0)) * 2.0)) +
        0.200000*tanh(((((((data$Fare) * (data$Age))) + ((((12.06482601165771484)) * (data$Pclass))))) * (((data$Sex) * (((data$Fare) + (cos(((((((7.0)) * (ifelse(rep(1.,NROW(data))*(data$Age > -998),data$Cabin,(((12.06482219696044922)) * (((data$Fare) + (data$Cabin)))))))) * 2.0)))))))))) +
        0.200000*tanh(sin((((data$Fare) * (ifelse(rep(1.,NROW(data))*(((data$Sex) * ((-1.0*((data$Cabin))))) > -998),ifelse(rep(1.,NROW(data))*(data$Age < -998),((data$Age) + (((((data$Cabin) * 2.0)) * 2.0))),((((data$SibSp) - (data$Sex))) - (((((data$Cabin) * (data$Fare))) / 2.0)))),data$Cabin)))))) +
        0.200000*tanh((-1.0*((((sin((ifelse(rep(1.,NROW(data))*((((((10.67747306823730469)) * ((((data$Fare) + ((-1.0*((data$Embarked)))))/2.0)))) + (data$Cabin)) > -998),((ifelse(rep(1.,NROW(data))*(((data$Cabin) + (((data$Pclass) - (data$Fare)))) > -998),(10.67746925354003906),data$Cabin)) * (data$Age)),data$Embarked)))) - (data$Embarked)))))) +
        0.200000*tanh(sin(((-1.0*(((((((((((((data$Fare) * 2.0)) + ((-1.0*((data$Age)))))/2.0)) + (((data$Sex) * 2.0)))/2.0)) + (((((cos(((((sin((((sin((data$Fare))) * 2.0)))) + (data$Sex))/2.0)))) - (data$Fare))) * (data$Age))))/2.0))))))) +
        0.200000*tanh(((((((((((((data$Fare) * 2.0)) * 2.0)) * 2.0)) * 2.0)) * 2.0)) * (sin((((tanh((cos((((data$Age) * (((data$Cabin) * (ifelse(rep(1.,NROW(data))*(data$Cabin < -998),tanh((data$Fare)),((((((data$Cabin) * 2.0)) * 2.0)) * 2.0))))))))))) * ((6.0)))))))) +
        0.200000*tanh(sin((((((ifelse(rep(1.,NROW(data))*(data$Cabin > -998),ifelse(rep(1.,NROW(data))*(data$Age > -998),data$Cabin,(4.37753391265869141)),((tanh((tanh((data$Cabin))))) + (data$SibSp)))) - (data$Parch))) + (((data$Fare) * ((((data$Cabin) + ((((((((-1.0*((data$Age)))) * 2.0)) * 2.0)) * 2.0)))/2.0)))))))) +
        0.200000*tanh(((((((((sin((ifelse(rep(1.,NROW(data))*(data$Cabin > -998),((((((data$SibSp) + (data$Fare))) + (data$SibSp))) + (data$SibSp)),(((data$Parch) + (((((data$Parch) + (((data$Fare) / 2.0)))) * (((data$Cabin) - (data$Embarked))))))/2.0))))) * 2.0)) * 2.0)) * 2.0)) * 2.0)) +
        0.200000*tanh(((((((((((((((sin((((((sin((((((((((data$Fare) * 2.0)) * 2.0)) - (data$Embarked))) * ((6.0)))))) - (tanh((tanh((data$Pclass))))))) * ((6.0)))))) * 2.0)) - (data$Pclass))) * 2.0)) * 2.0)) * 2.0)) * 2.0)) * 2.0)) +
        0.200000*tanh(((((((((sin((((((data$Fare) * 2.0)) * ((((5.0)) + (cos((((data$Age) * (ifelse(rep(1.,NROW(data))*((((5.0)) * (((((data$Age) * (data$Cabin))) * 2.0))) > -998),data$Pclass,((data$Fare) * (data$Cabin)))))))))))))) * 2.0)) * 2.0)) * 2.0)) * 2.0)) +
        0.200000*tanh(cos((((data$Fare) * (((((ifelse(rep(1.,NROW(data))*(((data$Cabin) * (data$Age)) < -998),((data$Cabin) + ((((11.45168018341064453)) * 2.0))),(11.45168018341064453))) - (((((((((data$Cabin) * (data$Age))) * (data$Age))) / 2.0)) / 2.0)))) - (tanh((((data$Parch) / 2.0)))))))))) +
        0.200000*tanh(cos((((((data$Fare) - (tanh((((((((((data$Embarked) / 2.0)) - (data$Age))) - (data$Age))) - (data$Age))))))) + (((data$Cabin) * (ifelse(rep(1.,NROW(data))*(data$Age > -998),cos(((((data$Age) + (data$Fare))/2.0))),((data$Embarked) - (data$Fare)))))))))) +
        0.200000*tanh(((sin((((data$Fare) + (((data$Fare) + ((-1.0*((((data$Pclass) * (data$Sex)))))))))))) + ((-1.0*((((((((data$Pclass) * (data$Fare))) * ((((((data$SibSp) + (data$Fare))) + (((data$SibSp) + (data$Sex))))/2.0)))) * (data$Parch)))))))) +
        0.200000*tanh(((((sin((((((((ifelse(rep(1.,NROW(data))*(data$Age > -998),ifelse(rep(1.,NROW(data))*(data$Cabin < -998),((data$Cabin) - (data$Age)),data$Fare),data$Age)) * (data$Cabin))) - (((ifelse(rep(1.,NROW(data))*(data$Age > -998),(-1.0*((data$Age))),data$Cabin)) - (data$Cabin))))) * (data$Fare))))) * 2.0)) * 2.0)) +
        0.200000*tanh(((cos((((data$Cabin) * (cos((ifelse(rep(1.,NROW(data))*(((data$Fare) * (data$Cabin)) < -998),data$Pclass,(((ifelse(rep(1.,NROW(data))*(data$Cabin > -998),data$Embarked,data$Fare)) + (ifelse(rep(1.,NROW(data))*(((data$Cabin) + (((data$Fare) * (data$Cabin)))) < -998),((data$Sex) * 2.0),data$Sex)))/2.0))))))))) * 2.0)) +
        0.200000*tanh(((sin(((((((((((((1.46239793300628662)) - (data$Sex))) + (sin((data$Parch))))) * (((sin((((data$Fare) * 2.0)))) * 2.0)))) * (data$SibSp))) + (data$Parch))))) * ((((((((data$SibSp) * (data$SibSp))) + (data$Parch))) + ((6.0)))/2.0)))) +
        0.200000*tanh(cos((((cos((((((data$Age) - (cos((((data$Fare) * (data$Cabin))))))) - (((data$Cabin) + (cos((tanh((data$Cabin))))))))))) + (((((data$Age) - (cos((((data$Sex) + (((data$Fare) * (data$Cabin))))))))) * 2.0)))))) +
        0.200000*tanh(((((((((cos((((((((((((8.93922901153564453)) - (((data$Fare) / 2.0)))) * (sin((data$Age))))) * ((13.17041110992431641)))) + (((data$Sex) - (sin(((8.93921470642089844)))))))/2.0)))) * ((8.93922138214111328)))) + (sin((data$Age))))) + (data$Sex))) * ((13.17040729522705078)))) +
        0.200000*tanh(ifelse(rep(1.,NROW(data))*(data$Age < -998),data$Sex,sin((((((cos((cos((cos((data$Sex))))))) + (data$Age))) * (((data$Cabin) + (ifelse(rep(1.,NROW(data))*(((((((data$Sex) + (data$Age))) + (cos(((12.04828929901123047)))))) * (data$Cabin)) < -998),data$Embarked,(12.04829311370849609)))))))))) +
        0.200000*tanh(((((sin((((((((((((ifelse(rep(1.,NROW(data))*(data$Cabin < -998),ifelse(rep(1.,NROW(data))*(data$Age > -998),data$Cabin,(((13.17909717559814453)) + (data$Fare))),sin((((((data$Age) * 2.0)) * 2.0))))) * (data$Fare))) * ((13.16840076446533203)))) - (data$Fare))) - ((13.16840076446533203)))) / 2.0)))) * 2.0)) * 2.0)) +
        0.200000*tanh((-1.0*((cos((((((((((((data$Age) - (data$Sex))) - ((-1.0*((cos((((data$Age) - (data$Parch)))))))))) - ((-1.0*((sin((data$Age)))))))) - (data$Cabin))) * (sin(((((sin((((data$Sex) / 2.0)))) + (data$Age))/2.0))))))))))) +
        0.200000*tanh(((((sin((((sin((((((((((((((data$SibSp) + (data$Pclass))/2.0)) + (data$Pclass))/2.0)) * (((((data$Age) * 2.0)) * (data$Cabin))))) - (data$Embarked))) + (((((data$Sex) - (data$Age))) * (data$Fare))))))) * 2.0)))) * 2.0)) * 2.0)) +
        0.200000*tanh(((sin((((ifelse(rep(1.,NROW(data))*(((data$Embarked) * (((data$Cabin) * 2.0))) < -998),((ifelse(rep(1.,NROW(data))*((((4.0)) * (((data$Cabin) * (data$Age)))) < -998),data$Pclass,((((data$Age) * (data$Cabin))) * ((11.41922855377197266))))) * 2.0),(((4.0)) * (data$Age)))) * 2.0)))) * 2.0)) +
        0.200000*tanh(sin((((data$Age) * (((data$Cabin) + ((((((((5.0)) + (((cos((data$Age))) + (data$Fare))))) + (ifelse(rep(1.,NROW(data))*(((data$Cabin) - (data$Fare)) > -998),(-1.0*((((((-1.0*((data$Parch)))) + (data$Fare))/2.0)))),data$SibSp)))) / 2.0)))))))) +
        0.200000*tanh(sin(((((ifelse(rep(1.,NROW(data))*(((data$Age) * (data$Cabin)) < -998),(((-1.0*((data$Sex)))) - (data$Sex)),((tanh((((((data$Parch) * (((data$Fare) + (tanh((sin((data$Age))))))))) * (data$Embarked))))) * (data$Cabin)))) + ((-1.0*((data$Sex)))))/2.0)))) +
        0.200000*tanh(cos(((((cos((((data$Age) * 2.0)))) + (((((((((data$Sex) + (((((((ifelse(rep(1.,NROW(data))*(data$Age < -998),(-1.0*((data$Parch))),(10.0))) * (data$SibSp))) * 2.0)) - (data$Parch))))) - (data$Parch))) + (data$Embarked))) + (cos((data$Age))))))/2.0)))) +
        0.200000*tanh(ifelse(rep(1.,NROW(data))*(data$Age > -998),ifelse(rep(1.,NROW(data))*(data$Embarked > -998),((((((((((sin(((((((8.0)) * ((((7.0)) * (data$Age))))) * (((sin((data$Fare))) * (data$Sex))))))) * 2.0)) * 2.0)) * 2.0)) * 2.0)) * 2.0),(7.0)),((data$Fare) - (data$Parch)))) +
        0.200000*tanh(((((((cos((((((((data$Age) + ((10.0)))) + (tanh(((((((14.93077468872070312)) + (tanh((tanh((data$Fare))))))) * (data$Age))))))) * (data$Cabin))))) * 2.0)) + (data$Embarked))) - (ifelse(rep(1.,NROW(data))*(data$Cabin > -998),data$Age,data$SibSp)))) +
        0.200000*tanh(cos((((((data$Pclass) - (((data$Fare) + (((data$Age) * 2.0)))))) * (((data$Age) * (((((ifelse(rep(1.,NROW(data))*(((data$Age) + (data$Embarked)) < -998),data$Embarked,data$Fare)) - (data$Embarked))) - ((((-1.0*((data$Cabin)))) - (data$Fare))))))))))) +
        0.193163*tanh(((sin((((ifelse(rep(1.,NROW(data))*(((data$Cabin) * (((ifelse(rep(1.,NROW(data))*((12.52592563629150391) < -998),data$Embarked,(((-1.0*((sin((data$Parch)))))) * 2.0))) * (data$Embarked)))) < -998),sin(((-1.0*((data$Sex))))),((((data$Embarked) * (data$Fare))) * ((12.52592563629150391))))) * 2.0)))) * 2.0)) +
        0.200000*tanh((-1.0*((cos((((ifelse(rep(1.,NROW(data))*(data$Embarked < -998),(10.0),ifelse(rep(1.,NROW(data))*(data$Age < -998),((data$Embarked) - (((data$SibSp) / 2.0))),((sin((sin((((tanh((((data$Embarked) - (data$SibSp))))) * (tanh((((data$Age) / 2.0)))))))))) / 2.0)))) * (data$Cabin)))))))) +
        0.200000*tanh(((((((sin(((((((13.88440036773681641)) * (((data$Age) - (tanh((ifelse(rep(1.,NROW(data))*(((((data$Fare) - (data$SibSp))) * (((data$Fare) * (data$Age)))) > -998),data$Fare,data$Age)))))))) + (((data$Embarked) * (data$Pclass))))))) * 2.0)) * 2.0)) * 2.0)) +
        0.200000*tanh(sin((((data$Embarked) * (((((data$Cabin) / 2.0)) * (((ifelse(rep(1.,NROW(data))*(data$Age > -998),sin((data$Fare)),ifelse(rep(1.,NROW(data))*(data$Cabin > -998),((data$Fare) * (data$Age)),((((data$Cabin) - ((1.0)))) * (sin((((data$Fare) - ((1.0)))))))))) / 2.0)))))))) +
        0.200000*tanh(cos((((((((sin((((data$Cabin) * (data$Cabin))))) + (data$Age))) / 2.0)) + (((((data$Fare) * (((data$Pclass) * (((((((data$Cabin) + (sin((data$Cabin))))) + (sin((data$Cabin))))) + (data$Age))))))) * (data$Age))))))) +
        0.200000*tanh((((8.0)) * ((((8.0)) * (((cos((ifelse(rep(1.,NROW(data))*(data$Age < -998),data$Embarked,data$Cabin)))) * (sin((((((data$Embarked) + (data$Fare))) * ((((((8.0)) * 2.0)) * (ifelse(rep(1.,NROW(data))*(((data$Age) + (data$Embarked)) < -998),data$Age,data$Cabin)))))))))))))) +
        0.200000*tanh(ifelse(rep(1.,NROW(data))*(((((data$Age) * 2.0)) * (data$Embarked)) > -998),cos((((((((data$Age) * 2.0)) * (ifelse(rep(1.,NROW(data))*(data$Age > -998),((((((((11.33305835723876953)) + ((((data$Age) + (data$Pclass))/2.0)))) + (data$Pclass))/2.0)) + ((9.0))),sin((data$Fare)))))) * 2.0))),data$Fare)) +
        0.200000*tanh(((ifelse(rep(1.,NROW(data))*(data$Embarked < -998),data$Parch,((((data$Sex) * 2.0)) - (data$Parch)))) * (((sin(((((4.0)) * (ifelse(rep(1.,NROW(data))*(data$Age < -998),((data$Cabin) * ((((3.0)) * (data$Fare)))),((data$Fare) - ((((3.0)) * (data$Age)))))))))) * 2.0)))) +
        0.200000*tanh(cos((((((((((((ifelse(rep(1.,NROW(data))*(data$Cabin < -998),sin((((data$Sex) - (tanh((data$Embarked)))))),data$Cabin)) + (((((data$Cabin) - (data$Pclass))) * 2.0)))/2.0)) - (data$SibSp))) * (data$Age))) + (((ifelse(rep(1.,NROW(data))*(data$Cabin < -998),data$Pclass,data$Age)) * 2.0)))/2.0)))) +
        0.200000*tanh(cos((((sin((data$SibSp))) + (((sin((data$SibSp))) + (((((data$Sex) * (data$Pclass))) + (((data$Age) * ((((14.84241867065429688)) + (ifelse(rep(1.,NROW(data))*(data$Age > -998),(5.0),((data$Fare) * ((-1.0*((cos((data$Sex))))))))))))))))))))) +
        0.200000*tanh(((((((sin(((6.0)))) / 2.0)) - (sin((((data$SibSp) * (sin((((data$Embarked) * (((ifelse(rep(1.,NROW(data))*(((((sin((data$Embarked))) + (((data$Age) + (data$Parch))))) + (data$Fare)) < -998),data$Age,data$Fare)) + (data$Age))))))))))))) * 2.0)) +
        0.189842*tanh(((((sin((((((((cos((cos((ifelse(rep(1.,NROW(data))*(data$Cabin > -998),data$Age,data$Sex)))))) - (data$Pclass))) + ((((((data$SibSp) - (data$Pclass))) + (ifelse(rep(1.,NROW(data))*(((data$Age) - (data$Cabin)) < -998),data$SibSp,(6.0))))/2.0)))) * (data$Cabin))))) * 2.0)) * 2.0)) +
        0.190154*tanh(ifelse(rep(1.,NROW(data))*(((data$SibSp) * (data$Cabin)) < -998),(((13.70917701721191406)) * (data$Age)),(-1.0*((((((((((data$Sex) - (((data$Sex) * (sin((sin((((data$Age) + (data$Age))))))))))) - (((data$Sex) * (data$Pclass))))) + (data$Age))) * 2.0)))))) +
        0.200000*tanh(cos((((data$Cabin) * (sin((((ifelse(rep(1.,NROW(data))*(((((data$Fare) * (((data$Embarked) * (data$Cabin))))) * (((data$Cabin) * (data$Cabin)))) < -998),((data$Embarked) * (((data$Fare) * (((data$Cabin) * (data$Cabin)))))),data$Age)) * (data$Age))))))))) +
        0.200000*tanh(((((((data$Sex) * 2.0)) * 2.0)) * ((-1.0*((((cos((data$Age))) + (sin((((((cos((data$Embarked))) * (data$SibSp))) - (((cos((ifelse(rep(1.,NROW(data))*(data$Age < -998),data$Fare,((((data$Sex) * (data$Fare))) * (data$Fare)))))) * 2.0))))))))))))) +
        0.197187*tanh(((((((((((sin((((data$Fare) * ((((data$Cabin) + (((ifelse(rep(1.,NROW(data))*(ifelse(rep(1.,NROW(data))*(((data$Age) * (data$Cabin)) > -998),(3.24589204788208008),data$Cabin) > -998),(3.24589204788208008),data$Cabin)) - ((((((data$Cabin) + (data$Age))/2.0)) / 2.0)))))/2.0)))))) * 2.0)) * 2.0)) * 2.0)) * 2.0)) * 2.0)) +
        0.200000*tanh(((((((sin((((tanh((((sin((((sin(((((((-1.0*((data$Fare)))) * 2.0)) + (data$Cabin))))) * 2.0)))) * 2.0)))) * 2.0)))) + (sin((((data$Parch) * 2.0)))))) - ((((data$Pclass) + (data$Parch))/2.0)))) + (cos((((data$Pclass) * 2.0)))))) +
        0.200000*tanh(((data$Cabin) * ((-1.0*((sin((ifelse(rep(1.,NROW(data))*(((data$Fare) * (((data$Cabin) * ((7.60528373718261719))))) > -998),((data$Fare) * (((data$Pclass) * (((data$Age) * (data$Cabin)))))),((data$Cabin) * (((sin((data$Fare))) - (sin((data$Age))))))))))))))) +
        0.200000*tanh(sin(((((((9.0)) * (((data$Age) + (((ifelse(rep(1.,NROW(data))*(data$Age < -998),(((data$Age) + ((9.0)))/2.0),(7.0))) - (data$Embarked))))))) * (ifelse(rep(1.,NROW(data))*(((data$Age) * (data$Embarked)) > -998),((((data$Fare) * 2.0)) * (data$Embarked)),((data$Fare) * 2.0))))))) +
        0.200000*tanh(((((-1.0*(((((data$Sex) + (((((((((((data$Pclass) * (((data$Pclass) * (data$Parch))))) + (data$Sex))) * 2.0)) * (data$Parch))) * (data$Parch))))/2.0))))) + (((data$Embarked) * (((sin(((((data$Sex) + (data$Cabin))/2.0)))) * 2.0)))))/2.0)) +
        0.200000*tanh(sin((((sin((((((data$Fare) + (data$Sex))) * (data$Age))))) * ((((ifelse(rep(1.,NROW(data))*(((((data$Age) * 2.0)) * (data$Cabin)) > -998),data$Cabin,((((((data$Cabin) * 2.0)) * (data$Cabin))) - (((data$Fare) * 2.0))))) + (((data$Fare) * 2.0)))/2.0)))))) +
        0.200000*tanh(((((data$Sex) * (cos(((((((9.66619300842285156)) * ((((((9.66619682312011719)) * (data$Age))) / 2.0)))) / 2.0)))))) + ((-1.0*((ifelse(rep(1.,NROW(data))*(data$Age < -998),data$Sex,((((data$Age) * (data$Sex))) * (((((data$Age) * (data$Sex))) * (data$Age))))))))))) +
        0.200000*tanh(((data$SibSp) * (ifelse(rep(1.,NROW(data))*(data$Cabin < -998),(((-1.0*((data$Pclass)))) * (data$SibSp)),((((data$Pclass) - ((((9.0)) * (data$Cabin))))) * (((sin((((data$Age) - (data$Cabin))))) * (((data$Pclass) - (((data$Cabin) * ((10.0)))))))))))))   )
  p<-1.0/(1.0+exp(-p))
}

gpComplex<-function(data)
{
  p<-(0.200000*tanh(Re(((((((((((((((((cosh((data$SibSp))) - (as.complex(4.0)))) + (((data$Age) + (cosh((data$Sex))))))) * 2.0)) * 2.0)) * (data$Age))) - (((((as.complex(5.0)) * (data$Sex))) * 2.0)))) - (cosh((data$Parch))))) - (cosh((data$SibSp)))))) +
        0.200000*tanh(Re((((((-((sin((tanh((data$Pclass)))))))) - (((data$Sex) + (cosh((((sqrt((((data$Age) - (data$Embarked))))) - (sqrt((sin((cosh((((data$Age) - (data$Embarked))))))))))))))))) * (cosh(((((as.complex(10.0)) + (data$Pclass))/2.0))))))) +
        0.200000*tanh(Re((((-(((((((-((((data$Sex) + (data$Age)))))) * (((data$SibSp) - (as.complex(4.90722036361694336)))))) * 2.0))))) - (((sinh((((((data$Pclass) + (tanh((sqrt((cosh((data$SibSp))))))))) * 2.0)))) + ((((-((data$Age)))) * (data$SibSp)))))))) +
        0.200000*tanh(Re((((((((-((sinh((((as.complex(4.91706228256225586)) - (data$SibSp)))))))) / ((((data$Age) + (data$Sex))/2.0)))) - (((data$SibSp) * (data$SibSp))))) - (((((((data$Age) + (sinh((data$SibSp))))) * (sinh((data$SibSp))))) / (sqrt((data$Sex)))))))) +
        0.200000*tanh(Re(((cosh((((data$Cabin) - (as.complex(10.0)))))) * (((((((data$Pclass) - (data$Cabin))) - (as.complex(4.0)))) * ((((((cosh((tanh(((((((data$Age) + (data$Sex))) + (data$Cabin))/2.0)))))) + (((data$Age) + (data$Sex))))/2.0)) + (data$Pclass)))))))) +
        0.200000*tanh(Re(((((((((((((sqrt((((data$Age) / 2.0)))) - (data$Sex))) - (((((data$Embarked) + (data$Age))) - (sinh((((data$Embarked) - (((cos((((data$Cabin) * (data$Pclass))))) + (data$Pclass))))))))))) - (data$Sex))) * 2.0)) * 2.0)) * 2.0))) +
        0.200000*tanh(Re(((data$Cabin) + (((data$Pclass) + (((as.complex(10.0)) * (((((as.complex(6.74915456771850586)) * (((data$Embarked) + (((((data$Fare) - (tanh((data$Pclass))))) - (((((tanh((tanh((data$Parch))))) / (data$Pclass))) - (data$Cabin))))))))) + (data$Embarked)))))))))) +
        0.200000*tanh(Re(((((((((((as.complex(10.0)) / (((((sinh(((-((sinh((data$Sex)))))))) - ((((((((data$Pclass) / (data$Age))) / (as.complex(10.0)))) + (data$SibSp))/2.0)))) - (data$Age))))) - (data$Parch))) - (data$Pclass))) - (data$SibSp))) - (data$Pclass)))) +
        0.200000*tanh(Re(((((((((((((((((((((((cosh((((as.complex(2.90926766395568848)) * (data$Cabin))))) - (((data$Sex) * (cosh((data$Fare))))))) - (data$Pclass))) * 2.0)) - (data$Age))) - (data$Fare))) - (data$Pclass))) * 2.0)) * 2.0)) * 2.0)) * 2.0)) - (as.complex(2.90926766395568848))))) +
        0.200000*tanh(Re(((((((as.complex(10.35072994232177734)) * 2.0)) + (data$Embarked))) / ((-((((((data$Sex) * 2.0)) + (((((((data$Sex) * (data$Age))) + ((((((data$SibSp) + (data$Age))/2.0)) + (data$SibSp))))) + (((tanh((tanh((data$SibSp))))) / (data$Age))))))))))))) +
        0.200000*tanh(Re(((((sin((data$Embarked))) + ((((((((((((((data$Fare) + (((data$Embarked) - (data$Pclass))))/2.0)) + (((((data$Cabin) - (((data$Age) / (cos((((sin((data$Fare))) * 2.0)))))))) - (data$SibSp))))) * 2.0)) * 2.0)) * 2.0)) * 2.0)))) * 2.0))) +
        0.200000*tanh(Re(((((sin((data$Sex))) + (((((sin((sin((((data$Sex) + ((((sin((data$Sex))) + (((data$Sex) / (data$Fare))))/2.0)))))))) * (data$Embarked))) / (data$Fare))))) / (((data$Pclass) / (sinh((((data$Fare) + (as.complex(7.0))))))))))) +
        0.200000*tanh(Re(((((data$Embarked) + (((((cos((cos(((((data$Sex) + (data$Embarked))/2.0)))))) / (tanh((cosh((sqrt((((data$Age) / (((((((data$Parch) + (data$Sex))/2.0)) + (data$Parch))/2.0)))))))))))) - (cos((cosh((data$Cabin))))))))) - (data$Sex)))) +
        0.200000*tanh(Re((((((((sin(((-((data$Fare)))))) - (data$Pclass))) / (cos((((as.complex(8.0)) * (cos((data$Fare))))))))) + ((((-((((data$Pclass) / (((sin((sqrt((data$Fare))))) - (data$Sex)))))))) * (((data$Fare) * (data$SibSp))))))/2.0))) +
        0.200000*tanh(Re(((((cos((((data$Fare) + (data$SibSp))))) / ((((data$Parch) + (data$Fare))/2.0)))) + (((((cosh((data$Age))) - (cosh((((data$Pclass) - (((tanh((sqrt((data$Age))))) + (cosh((data$Age))))))))))) * (data$Sex)))))) +
        0.200000*tanh(Re(((((cos((data$Age))) / (tanh((cos((data$Parch))))))) + (((sin((((data$Cabin) + (((data$Age) - (((cos(((((data$Pclass) + (cos((tanh((cos((data$SibSp))))))))/2.0)))) / (data$Age))))))))) / (((data$Embarked) / 2.0))))))) +
        0.200000*tanh(Re(((data$Parch) / (((((data$Fare) * ((((tanh(((-((((((cos((data$Fare))) / (data$Age))) + (as.complex(2.66359162330627441))))))))) + (((cos((((data$Fare) * 2.0)))) / (data$Age))))/2.0)))) * (((cos((data$Fare))) * (data$Pclass)))))))) +
        0.200000*tanh(Re(((((((cosh((data$Cabin))) * 2.0)) - (((sinh((data$Parch))) * (data$Age))))) + (sinh(((((((cos((cosh((((((sin((sinh((data$Age))))) * 2.0)) * 2.0)))))) + (data$Age))/2.0)) / (((((data$Pclass) / 2.0)) / 2.0))))))))) +
        0.200000*tanh(Re((((-((sinh((data$SibSp)))))) / (((tanh((data$Pclass))) - (((sin((data$Age))) * (((cosh((((data$Pclass) / (((((((((((sqrt((data$Fare))) + (tanh((data$Age))))) + (data$Embarked))) * 2.0)) * 2.0)) * 2.0)))))) * 2.0))))))))) +
        0.200000*tanh(Re(((sinh((data$Parch))) / (((cos((((cos((sin((cos(((((data$Age) + (((((((data$Fare) + (cosh((data$Cabin))))/2.0)) + (data$Cabin))/2.0)))/2.0)))))))) / (data$Cabin))))) - (cos((((((data$Age) * (data$Fare))) * 2.0))))))))) +
        0.200000*tanh(Re(cos(((((-((((((data$Cabin) * 2.0)) + (cos((((data$Fare) / (((cos((data$Fare))) / (data$Cabin)))))))))))) - ((((((((cos((data$Fare))) * 2.0)) / (data$Fare))) + ((-((((((data$Fare) * 2.0)) / (data$Cabin)))))))/2.0))))))) +
        0.200000*tanh(Re(((cos((((data$Fare) * 2.0)))) * ((((((((((cosh((((((data$Fare) * (data$Fare))) + (sinh((data$Embarked))))))) + (data$Sex))/2.0)) + (((data$Pclass) + (data$Age))))) / (tanh((data$Sex))))) * (((data$Age) + (data$Embarked)))))))) +
        0.200000*tanh(Re(((((((sin((((sqrt((sin((((data$Pclass) / ((-((data$Fare)))))))))) * 2.0)))) * 2.0)) + (sqrt((sin((((data$Pclass) / (data$Fare))))))))) / (((data$Cabin) / (sqrt((((cos((data$Cabin))) * (cos((data$Fare)))))))))))) +
        0.200000*tanh(Re(((((cosh((data$Embarked))) + (((data$Sex) / (((data$Embarked) - (tanh((data$Age))))))))) + (((data$Parch) / (((cosh((tanh((data$Age))))) * ((-((((data$Pclass) * (cos((((sinh((data$Embarked))) - (data$Age))))))))))))))))) +
        0.200000*tanh(Re((-((cos((((((((data$Fare) / (((data$Sex) + (sin((data$Fare))))))) + ((((((((data$Fare) * (data$Sex))) + (data$SibSp))/2.0)) + ((((((((as.complex(9.0)) * 2.0)) / (data$Fare))) + (((as.complex(10.88791179656982422)) / (data$Cabin))))/2.0)))))) / 2.0)))))))) +
        0.200000*tanh(Re(((((((tanh((data$SibSp))) / (((data$Cabin) * (data$Age))))) / (data$Cabin))) - (((((((((data$Cabin) * (data$Age))) + (((data$Cabin) + (data$SibSp))))) + (data$Sex))) - (((data$SibSp) / (((data$SibSp) + (data$Age)))))))))) +
        0.200000*tanh(Re(((data$Sex) * ((((-((sin((data$Fare)))))) + (((((-(((((((data$Embarked) + (data$Fare))/2.0)) / (sin((data$Fare)))))))) + ((((data$Cabin) + (((data$Fare) / ((((data$Pclass) + (sin((tanh(((-((data$Fare)))))))))/2.0)))))/2.0)))/2.0))))))) +
        0.200000*tanh(Re(((tanh((data$Embarked))) + (((data$Embarked) + ((((((-((((((cos((data$Embarked))) / (data$Age))) - (tanh((data$Parch)))))))) * (data$Fare))) / ((((data$Age) + ((((tanh(((-((data$Age)))))) + (sinh((data$Embarked))))/2.0)))/2.0))))))))) +
        0.200000*tanh(Re(((cos((((((data$Cabin) + (data$Fare))) * (((data$Fare) + (tanh((((data$Age) + (data$Fare))))))))))) / (((((data$Fare) - (data$Age))) / (((cosh((as.complex(7.0)))) * (cos((((cos((data$SibSp))) / (data$Age)))))))))))) +
        0.200000*tanh(Re(((((((((((sinh((((((((data$Age) * 2.0)) * 2.0)) * 2.0)))) * 2.0)) * 2.0)) * 2.0)) / (data$Parch))) * (((data$Sex) * (((data$Pclass) * (cos((sqrt(((-((((((data$Cabin) / (data$Age))) - (data$Cabin))))))))))))))))) +
        0.200000*tanh(Re((((((-((cos((cosh((((sqrt((((data$Parch) + (data$SibSp))))) + (data$Fare)))))))))) * (((cosh((data$Fare))) + (((sin((data$SibSp))) + (data$Embarked))))))) * (((cosh((data$SibSp))) + (((data$Fare) + (data$Parch)))))))) +
        0.200000*tanh(Re(((((data$Sex) / (data$Pclass))) + ((-((((((((((((data$Sex) + (((data$Fare) / (cos((data$Age))))))/2.0)) + (data$Sex))/2.0)) - (cos((((data$SibSp) / (data$Age))))))) + (cos((((data$Pclass) / (cos((data$Age))))))))))))))) +
        0.200000*tanh(Re(((sqrt((data$SibSp))) / (((((cos((((data$Fare) / 2.0)))) / (sin((data$Cabin))))) - (tanh((((sqrt((((((sin((((cos((data$Age))) / (data$Cabin))))) - (data$Cabin))) + (data$Pclass))))) + (data$Pclass)))))))))) +
        0.200000*tanh(Re(((sinh((sinh((data$Embarked))))) * (((data$Parch) / ((((((((((((cosh((tanh((data$Sex))))) + (((data$Fare) / (sin((data$Embarked))))))/2.0)) + (((sin((data$Sex))) / (data$Cabin))))/2.0)) + (data$Sex))/2.0)) * (cos((data$Cabin)))))))))) +
        0.200000*tanh(Re(((cos(((((((((sqrt((((data$Embarked) + (data$SibSp))))) + (data$Pclass))/2.0)) / (data$Age))) - (data$Sex))))) + (((((((((cos((data$Embarked))) + (data$Pclass))/2.0)) + (((data$Age) + (((data$Cabin) + (data$Sex))))))/2.0)) / (data$Pclass)))))) +
        0.200000*tanh(Re(((cosh((((((((data$Embarked) * (data$Embarked))) * (data$Embarked))) + (((data$Fare) / (data$Cabin))))))) * (((((data$Sex) * (((((data$Fare) / ((((data$Cabin) + (((data$Fare) * (data$Fare))))/2.0)))) * (data$Embarked))))) / (data$Cabin)))))) +
        0.200000*tanh(Re(((sin(((((((data$Embarked) / (cos((((tanh((data$SibSp))) / (tanh((data$Age))))))))) + (data$Age))/2.0)))) * (((((((data$Embarked) / (data$SibSp))) - (data$Cabin))) - (cosh((((cos((tanh((data$Age))))) / (data$Age)))))))))) +
        0.200000*tanh(Re(((((((((data$Age) - (cos((data$Age))))) / (cos((((((((as.complex(8.08032131195068359)) * (data$Fare))) * (data$Fare))) + (data$Fare))))))) / ((((((((as.complex(9.0)) * (data$Fare))) * (data$Fare))) + ((-((as.complex(0.70082920789718628))))))/2.0)))) / (data$Parch)))) +
        0.200000*tanh(Re(cos((((((sinh((data$Age))) * 2.0)) + (((((data$Fare) * (cosh((data$Cabin))))) * (((sqrt((((data$Age) + (((sqrt((((data$Pclass) * 2.0)))) + (((data$Age) - (sinh((((as.complex(10.04762935638427734)) / 2.0)))))))))))) + (as.complex(10.04763317108154297))))))))))) +
        0.200000*tanh(Re(sin((((((((sinh((((data$SibSp) * 2.0)))) + (sqrt((((data$Parch) - (cosh((((as.complex(7.0)) + (sqrt((cos((data$Fare))))))))))))))/2.0)) + (((data$Sex) / (sin((cosh((((cos((data$Fare))) - (as.complex(7.0)))))))))))/2.0))))) +
        0.200000*tanh(Re(sin((((sinh((((data$Fare) - (((sinh((as.complex(2.44588184356689453)))) * (cos((data$Age))))))))) - (((((((data$Fare) - ((((as.complex(6.0)) + (cos((data$Age))))/2.0)))) * (data$Cabin))) - (sinh((((data$Sex) * (data$Pclass)))))))))))) +
        0.200000*tanh(Re((((((((data$Embarked) / ((((data$Fare) + (((data$Embarked) - (data$Pclass))))/2.0)))) + (((((((((((data$Embarked) - (data$Age))) / ((((data$Age) + (((data$Fare) / 2.0)))/2.0)))) + (data$SibSp))/2.0)) + (data$SibSp))/2.0)))/2.0)) / (((data$Age) - (data$Fare)))))) +
        0.200000*tanh(Re(((data$Embarked) * ((((((((((sqrt((data$Age))) / (data$Fare))) / (data$Age))) / (cos((data$Fare))))) + (((((cos((data$Fare))) + (cos((as.complex(13.04413604736328125)))))) / (cos((cosh((((sqrt((sinh((data$Age))))) * 2.0)))))))))/2.0))))) +
        0.200000*tanh(Re(((cos((sinh((sinh((sin((((data$Fare) / (sin((sin((data$Embarked))))))))))))))) / (sin((sin((((sinh((cos((sin((sinh((data$Sex))))))))) / (sin(((((((data$Embarked) / (data$Fare))) + (as.complex(7.0)))/2.0))))))))))))) +
        0.200000*tanh(Re(cos(((((((data$SibSp) + (sqrt((((((data$Fare) / (((data$Fare) - (((data$Fare) / (sinh((data$Age))))))))) - (((data$Fare) / (((data$Age) / 2.0)))))))))/2.0)) - (((((data$Fare) / (sinh((data$Age))))) + (data$Fare)))))))) +
        0.200000*tanh(Re(((cos((((data$Cabin) * (data$Age))))) * ((((((((data$Parch) + (data$Cabin))/2.0)) + (data$Cabin))) / (((data$Age) / (((data$Sex) * (((((data$SibSp) + (data$SibSp))) * (((((data$SibSp) + (data$Sex))) + (data$Embarked)))))))))))))) +
        0.200000*tanh(Re(((((((((tanh((sin((data$Age))))) * (as.complex(8.0)))) / (data$Sex))) / (sin((((data$Age) * (as.complex(9.0)))))))) + ((((((data$Sex) / (sin((((cos((data$Fare))) * (as.complex(9.0)))))))) + (((data$Age) * (as.complex(9.0)))))/2.0))))) +
        0.200000*tanh(Re((((((((data$Age) + (((data$Fare) / (sin((data$Age))))))/2.0)) - (((((((data$Parch) / (data$Fare))) + (data$Fare))) + (((data$Fare) + (((data$Fare) * (data$Fare))))))))) * (((data$Sex) + ((((data$SibSp) + (data$Age))/2.0))))))) +
        0.200000*tanh(Re(((((data$Age) / (((cos((((((tanh((data$Age))) / 2.0)) / (cos((data$Age))))))) / 2.0)))) / (((data$Fare) - (cos(((((((((data$Age) * (tanh((sin((data$Age))))))) + (((as.complex(13.09249401092529297)) / (data$Fare))))/2.0)) / 2.0))))))))) +
        0.200000*tanh(Re(((((data$Cabin) * ((-(((((((tanh((sqrt((data$Parch))))) + (((sqrt(((-((sin((data$SibSp)))))))) - (data$Cabin))))/2.0)) * (((cosh((cosh((((sqrt((data$Parch))) - (data$Fare))))))) * 2.0))))))))) * (data$SibSp)))) +
        0.200000*tanh(Re(cos((((data$Fare) - (((((data$Cabin) * ((((data$Cabin) + ((((((data$Cabin) + (as.complex(13.22632980346679688)))) + (((cos(((((((data$Age) * (data$Embarked))) + (data$Cabin))/2.0)))) * 2.0)))/2.0)))/2.0)))) - ((-((((((data$Embarked) * 2.0)) / (data$Age))))))))))))) +
        0.200000*tanh(Re(((((data$Embarked) / ((((((((((((data$Age) + (((((data$Fare) / (data$Age))) * 2.0)))/2.0)) + (data$Sex))/2.0)) / 2.0)) + (data$Sex))/2.0)))) / (((((((((((sinh((sin((((data$Fare) * 2.0)))))) / 2.0)) / 2.0)) / 2.0)) / 2.0)) / (data$Age)))))) +
        0.200000*tanh(Re(((((data$Fare) + (((data$Fare) + (sinh(((((cosh((data$Embarked))) + (((data$Fare) * (((as.complex(7.07559394836425781)) * ((-((data$Cabin)))))))))/2.0)))))))) / (tanh((tanh((sin((((data$Fare) * (((as.complex(7.07559394836425781)) * ((-((data$Cabin))))))))))))))))) +
        0.200000*tanh(Re(((sqrt((data$Fare))) / ((((-((data$Pclass)))) / (((data$Parch) + (((cos((((cos((((((cos((sqrt((sqrt((((data$Fare) * 2.0)))))))) - (((data$Embarked) * 2.0)))) - (data$Fare))))) - (data$Age))))) - (data$Sex)))))))))) +
        0.200000*tanh(Re((((-((((((data$Cabin) + (data$SibSp))) + (data$Fare)))))) / ((((((((data$Fare) + (data$Sex))) * (((as.complex(5.0)) + ((-((((((((data$Fare) + (data$SibSp))) + (data$Cabin))) + (data$Fare)))))))))) + (data$Sex))/2.0))))) +
        0.200000*tanh(Re((-(((((((data$Sex) / (cosh((tanh((sqrt((data$Age))))))))) + (((cosh((data$Age))) / (((data$Age) + (((((((data$Sex) / (sqrt((data$Age))))) / (cosh((sqrt((data$Age))))))) + (data$Pclass))))))))/2.0)))))) +
        0.200000*tanh(Re(((data$SibSp) / (((data$Age) - ((((data$Cabin) + ((((((cos((((((data$Age) * ((((data$Pclass) + (data$Cabin))/2.0)))) * (data$SibSp))))) / 2.0)) + (sin((sinh((cos((((data$Age) + (((data$SibSp) + (data$Cabin))))))))))))/2.0)))/2.0))))))) +
        0.200000*tanh(Re(((((data$SibSp) + (((((((((((data$Parch) / (data$Age))) * (data$SibSp))) - (data$Cabin))) - (data$Pclass))) - (((data$Age) + (sqrt((data$Parch))))))))) + (((((data$Fare) / (((data$Age) + (data$SibSp))))) / (data$Cabin)))))) +
        0.200000*tanh(Re((((((((-((cos((((sin((data$Pclass))) / (data$Fare)))))))) * (sinh((data$Age))))) * (cosh(((((data$Pclass) + (((sin((data$Embarked))) / (data$Fare))))/2.0)))))) + (cos((((data$Pclass) / (sin((data$Fare)))))))))) +
        0.200000*tanh(Re((((((cos((data$Fare))) / (((((data$Embarked) / 2.0)) + (data$Fare))))) + ((((data$Embarked) + (((((((data$Age) / (data$Fare))) / (data$Embarked))) / (((tanh((((sin((sinh((((data$Age) * 2.0)))))) * 2.0)))) + (data$Fare))))))/2.0)))/2.0))) +
        0.200000*tanh(Re(((sin((((tanh((tanh((tanh((data$SibSp))))))) / (data$Age))))) / (((data$Fare) / ((((((data$Parch) / (((data$Fare) - (tanh((data$Sex))))))) + (((data$Embarked) + (cosh((((data$Parch) / (sin((data$Cabin))))))))))/2.0))))))) +
        0.200000*tanh(Re(((((((((((((data$Sex) / (((sin((data$Fare))) - (((data$SibSp) + (data$Age))))))) + (data$Sex))/2.0)) + (data$Age))/2.0)) * (cosh((as.complex(4.75296831130981445)))))) * (((((data$Pclass) - (sinh((data$Cabin))))) - (data$Fare)))))) +
        0.200000*tanh(Re(((data$Cabin) * (((((data$Sex) + (((data$SibSp) + (((data$Parch) + (((data$Cabin) / (((as.complex(9.24114227294921875)) + (((((as.complex(9.24114227294921875)) + (((tanh((data$Fare))) / 2.0)))) * (data$Cabin))))))))))))) / (((tanh((data$Fare))) - (data$Age)))))))) +
        0.200000*tanh(Re((((-((cosh((cosh((sin((data$Fare)))))))))) + (((((((cosh((data$Fare))) * 2.0)) - (((data$Sex) - (cosh((data$Fare))))))) * (cos((cosh((((((sinh((cosh((data$Sex))))) - (data$Fare))) * 2.0))))))))))) +
        0.200000*tanh(Re((((((((data$Parch) + (sqrt((sin((data$Embarked))))))/2.0)) * 2.0)) / (((((tanh((as.complex(0.11361482739448547)))) * (((data$Cabin) - (cos((((sin((sqrt((data$Age))))) * (((sin((data$Age))) * 2.0)))))))))) - (((sin((data$Age))) * 2.0))))))) +
        0.200000*tanh(Re((((sin((((((data$Age) + (sqrt((((sin((data$Cabin))) / (((data$Age) - (cos((sqrt((data$Embarked))))))))))))) / ((((data$Cabin) + (data$Embarked))/2.0)))))) + (((data$Embarked) * (((data$Parch) + (((data$Cabin) + (data$Parch))))))))/2.0))) +
        0.200000*tanh(Re((((((cosh((((((data$Fare) * 2.0)) * (((data$Age) + (as.complex(11.41170787811279297)))))))) + (as.complex(3.0)))/2.0)) / (((cos((data$Fare))) / (sin(((((((cosh((((data$Fare) * (as.complex(11.41170787811279297)))))) + (data$Cabin))/2.0)) / (sin((((data$Fare) * 2.0))))))))))))) +
        0.200000*tanh(Re(((data$SibSp) / ((((((((data$Parch) / (cosh(((((data$Fare) + (((((((((data$Fare) + (sinh((data$Embarked))))/2.0)) / (data$Pclass))) + (data$SibSp))/2.0)))/2.0)))))) + (cos((sinh((data$Embarked))))))/2.0)) - (((((data$Fare) + (data$Pclass))) * 2.0))))))) +
        0.200000*tanh(Re(((((cosh((data$Cabin))) / (((data$SibSp) * 2.0)))) / (((cosh((((data$Cabin) * 2.0)))) - (cosh(((((data$Fare) + (((((((((data$SibSp) + (data$Sex))/2.0)) + (((data$Cabin) * ((((data$Cabin) + (data$Parch))/2.0)))))/2.0)) - (data$SibSp))))/2.0))))))))) +
        0.200000*tanh(Re(sin(((((((((data$Embarked) / (((((((data$Parch) + (sqrt((data$Parch))))/2.0)) + (((data$Fare) * 2.0)))/2.0)))) * ((((sin((cos((data$Embarked))))) + (sqrt((data$Embarked))))/2.0)))) + ((((-((data$Sex)))) + (sqrt(((-((data$Fare)))))))))/2.0))))) +
        0.200000*tanh(Re(((((((data$Embarked) - (data$Pclass))) / 2.0)) - ((((((((((((data$Embarked) - (data$Sex))) - (sinh((data$SibSp))))) / 2.0)) / (((((((data$SibSp) + (data$Pclass))/2.0)) + (sinh((sinh((data$Age))))))/2.0)))) + (sinh((sinh((data$Age))))))/2.0))))) +
        0.200000*tanh(Re(((sin((data$SibSp))) / (((((sin(((((-((((sinh((data$Fare))) * 2.0))))) * 2.0)))) - (data$Age))) / (((((-((data$Pclass)))) + (((((data$SibSp) / 2.0)) / (sin(((((-((((sinh((data$Fare))) * 2.0))))) * 2.0)))))))/2.0))))))) +
        0.200000*tanh(Re((-((((((sin((sqrt((((((data$Age) / 2.0)) / ((((((((data$Pclass) + (data$Fare))/2.0)) / (((sqrt((data$Pclass))) + (sqrt((data$Sex))))))) / (data$Cabin))))))))) / (cos((data$Fare))))) / (cosh((data$Pclass))))))))) +
        0.200000*tanh(Re((((((((((sinh((cos((sinh((((data$Age) - (data$Pclass))))))))) * (((data$Age) + (((data$Parch) + (cosh((data$Age))))))))) * (((data$Embarked) + (cosh((((data$Age) + (data$Age))))))))) + (data$Cabin))/2.0)) + (data$Cabin)))) +
        0.200000*tanh(Re(((((((sqrt((data$Age))) * (sinh((((data$SibSp) * 2.0)))))) + (((((data$Fare) + (data$Pclass))) + (((((((data$Sex) + (data$Pclass))/2.0)) + (data$Pclass))/2.0)))))) / (cos((((sinh((((sqrt((data$Age))) * 2.0)))) * (as.complex(12.11184978485107422))))))))) +
        0.186716*tanh(Re(((((((sin(((((((sinh((data$Sex))) + (((((((((((((data$Age) * (sinh((data$Age))))) + (data$Sex))/2.0)) + (data$Fare))/2.0)) * (((data$Age) * (data$Sex))))) / (data$Parch))))/2.0)) / ((-((data$Age)))))))) * 2.0)) * 2.0)) * 2.0))) +
        0.200000*tanh(Re(((((data$Cabin) / (data$Pclass))) / (((((((data$Pclass) + (((((data$Cabin) / (data$Pclass))) / 2.0)))) - (((data$Cabin) + (sin((data$Age))))))) * (((data$Pclass) + (cos((((as.complex(12.86872005462646484)) / (data$Age)))))))))))) +
        0.200000*tanh(Re((((((((sin((data$Pclass))) + (sin((data$Parch))))/2.0)) + ((((((data$Embarked) / (data$SibSp))) + ((-((cos(((((data$SibSp) + (data$Age))/2.0))))))))/2.0)))) / (((cos((((((data$SibSp) * 2.0)) / (data$Age))))) * (data$Fare)))))) +
        0.200000*tanh(Re(sin(((((((((data$Parch) / 2.0)) + (cosh(((((cos(((((cos((((cosh((data$Fare))) / 2.0)))) + (data$Fare))/2.0)))) + (data$Fare))/2.0)))))/2.0)) * (((((((cos((data$Fare))) / 2.0)) / (sin((data$Fare))))) / (sin((data$Fare)))))))))) +
        0.200000*tanh(Re(((((cosh((((data$Fare) - (as.complex(12.63686943054199219)))))) * (((cos((cosh((data$Pclass))))) / (cos((cosh((data$Fare))))))))) * (((sin((cosh((((cosh((data$Fare))) - (as.complex(12.63686943054199219)))))))) / ((-((data$Fare))))))))) +
        0.200000*tanh(Re(((((data$Pclass) / (((((((data$Embarked) + (data$Embarked))/2.0)) + (cos((data$Pclass))))/2.0)))) / (((data$Sex) * (((((sin((((sinh((cosh(((((((data$Age) * 2.0)) + (as.complex(4.0)))/2.0)))))) + (tanh((sin((data$Age))))))))) * 2.0)) * 2.0))))))) +
        0.200000*tanh(Re((-(((((((((sin(((((((tanh((data$Cabin))) + (data$Cabin))) + (tanh((((tanh((data$Cabin))) + ((((data$Age) + (data$Fare))/2.0)))))))/2.0)))) + (data$Sex))/2.0)) / (sqrt(((((data$Fare) + (sin((data$Age))))/2.0)))))) * (data$Fare))))))) +
        0.200000*tanh(Re(((((data$Embarked) * ((((((data$Fare) + (cos((data$Cabin))))/2.0)) * (data$Parch))))) * (((((((((data$Fare) + (data$Embarked))/2.0)) + (data$Sex))/2.0)) + (((((((((data$Parch) * (data$Embarked))) / (data$Cabin))) + (data$Sex))) + (data$Parch)))))))) +
        0.200000*tanh(Re(sin(((((((((((((((data$Fare) / (data$Age))) + (data$Pclass))/2.0)) * (data$Fare))) + (((((data$Sex) * (data$Pclass))) / (data$Age))))/2.0)) + ((((((((data$Fare) * (data$Pclass))) / (cos((data$Pclass))))) + (cos((data$Parch))))/2.0)))/2.0))))) +
        0.200000*tanh(Re(((((((sin((sin((data$SibSp))))) / ((((-((data$Age)))) / (data$Embarked))))) - (((((data$Embarked) / (cos((data$Cabin))))) / (data$Cabin))))) / (sin((((data$Sex) + (((((data$Age) * 2.0)) + (((data$Age) * 2.0))))))))))) +
        0.200000*tanh(Re((-((((data$Embarked) / (cos((((((as.complex(3.37635827064514160)) / (data$Age))) + (((((-((((data$Age) * 2.0))))) + (sin(((((((data$SibSp) / (data$Age))) + (cos((((data$Age) / (sqrt((data$Sex))))))))/2.0)))))/2.0)))))))))))) +
        0.200000*tanh(Re(sqrt((((((data$Fare) - (data$Sex))) - (cosh((sqrt(((((((((((((((data$Embarked) / 2.0)) / (data$Age))) / 2.0)) / (((data$Fare) - (data$Sex))))) + (data$Sex))/2.0)) * (((data$Embarked) / (((data$Fare) - (data$Age)))))))))))))))) +
        0.200000*tanh(Re(((((data$Fare) + (((sin((((data$Sex) - (sinh((((as.complex(10.45747852325439453)) * (cos((data$Fare))))))))))) * 2.0)))) + ((((cos((data$Fare))) + (((data$Age) * (((as.complex(10.45748519897460938)) * (cos((cosh((((as.complex(10.45748519897460938)) * (data$Fare))))))))))))/2.0))))) +
        0.200000*tanh(Re((((-((sqrt((((data$Pclass) + (((data$Sex) + (data$Fare)))))))))) + (((data$SibSp) * (((data$Parch) * (((((data$Sex) + (((data$Pclass) + (sin((((data$Pclass) + (((data$Fare) + (data$Pclass))))))))))) - (data$SibSp)))))))))) +
        0.200000*tanh(Re(((sin((((data$Embarked) / (tanh((sin(((((((((data$Embarked) / (sin((sinh((data$Fare))))))) * 2.0)) + (tanh((data$Sex))))/2.0)))))))))) * ((((data$Embarked) + (((cosh((sinh((data$Embarked))))) + (((data$Sex) / (data$Embarked))))))/2.0))))) +
        0.200000*tanh(Re(((data$Age) / (((as.complex(2.84598183631896973)) - (((((((((((tanh((((data$Age) - (data$Parch))))) + ((((data$Embarked) + (((as.complex(0.61022412776947021)) - (data$Parch))))/2.0)))/2.0)) + (as.complex(14.96731662750244141)))) * (sin((data$Age))))) + (((data$Sex) - (sin((data$Age))))))/2.0))))))) +
        0.200000*tanh(Re(((((((sin((((cosh((((data$Fare) - (as.complex(5.71034574508666992)))))) / 2.0)))) * 2.0)) * 2.0)) * ((((-((((((as.complex(6.0)) / (data$Sex))) / (((data$SibSp) / (data$Age)))))))) - ((((((cos((data$Age))) / (data$SibSp))) + (as.complex(5.71034193038940430)))/2.0))))))) +
        0.200000*tanh(Re(((data$Parch) / (((cosh((tanh((((data$Age) * (sin((data$Cabin))))))))) * (((data$Cabin) * ((((((((data$Cabin) * (cosh((sin((((sin((data$Cabin))) * (sqrt((data$Age))))))))))) + (data$Sex))/2.0)) / (data$Age)))))))))) +
        0.200000*tanh(Re(((((((((((data$Embarked) / (data$Fare))) + ((((cosh((data$Fare))) + (((((data$Sex) * (data$Embarked))) / ((((data$Age) + (data$Embarked))/2.0)))))/2.0)))/2.0)) / 2.0)) + (((((data$Embarked) * (data$Sex))) / ((((data$Age) + ((-((data$Fare)))))/2.0)))))/2.0))) +
        0.200000*tanh(Re(cos(((((((((-((((((((((data$SibSp) / (data$Parch))) + (cos((((data$Cabin) / (data$Age))))))/2.0)) + (data$Cabin))/2.0))))) + (data$Sex))) * (data$Age))) + (((cosh((data$Sex))) * (cos((((data$Cabin) / (data$Age)))))))))))) +
        0.200000*tanh(Re(((((data$SibSp) / (((cos((data$SibSp))) * (((data$Fare) * (((((((data$Pclass) - ((((data$Age) + ((((data$Sex) + ((((sqrt((cos((data$Sex))))) + (data$SibSp))/2.0)))/2.0)))/2.0)))) - (data$Fare))) - (sin((data$Age))))))))))) / 2.0))) +
        0.200000*tanh(Re(((as.complex(3.77948737144470215)) / (((((((((((((sin((data$Age))) / ((-(((((data$Fare) + (data$Pclass))/2.0))))))) / 2.0)) - (sin((((data$Fare) + (data$Sex))))))) - (as.complex(3.77949094772338867)))) - (as.complex(3.77949094772338867)))) + (sinh((((data$Age) * (as.complex(3.77948737144470215))))))))))) +
        0.200000*tanh(Re(((((data$Parch) / (cos((((sinh((data$Pclass))) / (cos((((cosh((data$Fare))) - (data$Age))))))))))) - ((((sinh((data$Sex))) + (((data$Pclass) / (cos((((data$Pclass) / (((cosh((data$Fare))) - (data$Age))))))))))/2.0))))) +
        0.200000*tanh(Re(((((((data$Embarked) / (((((data$Fare) * (data$Fare))) * 2.0)))) - (sin((cosh((((data$Fare) * (data$Pclass))))))))) / (((data$Embarked) - (sin((sin((sinh(((-((((((data$Fare) * (as.complex(9.0)))) - (data$Pclass))))))))))))))))) +
        0.200000*tanh(Re(((sqrt((data$Fare))) * ((((((data$SibSp) * ((((((((data$Pclass) / (data$Age))) + (((sqrt((data$SibSp))) / (((data$Age) - (data$Fare))))))/2.0)) - (data$SibSp))))) + (((((data$Sex) / (cos((data$Age))))) / (data$Pclass))))/2.0))))))
  p<-1.0/(1.0+exp(-p))
}

ytrainpreds = data.frame(c1=gpReal(slice(y,1:length(ysurvived))),c2=gpComplex(slice(ycomplex,1:length(ysurvived))),Survived=ysurvived)
ytrainpreds$s<-(ytrainpreds$c1+ytrainpreds$c2)/2.
print(logLoss(ytrainpreds$Survived,ytrainpreds$c1))
print(accuracy(ytrainpreds$Survived,round(ytrainpreds$c1,digits=0)))
print(logLoss(ytrainpreds$Survived,ytrainpreds$c2))
print(accuracy(ytrainpreds$Survived,round(ytrainpreds$c2,digits=0)))
print(paste('Corr:',cor(ytrainpreds$c1,ytrainpreds$c2)))
print(logLoss(ytrainpreds$Survived,.5*ytrainpreds$c1+.5*ytrainpreds$c2))
print(accuracy(ytrainpreds$Survived,round(.5*ytrainpreds$c1+.5*ytrainpreds$c2,digits=0)))

ggplot(ytrainpreds,aes(x=c1,y=c2,colour=factor(Survived)))+geom_point(size=5,shape=18)+labs(x='Real',y='Complex',title='Scatter Plot',colour = "Survived")+theme_bw()

df_final <- data.frame(PassengerId = passengerids, Survived=round(.5*gpReal(slice(y,nrow(ytrainpreds)+1:nrow(y)))+.5*gpComplex(slice(ycomplex,nrow(ytrainpreds)+1:nrow(ycomplex))),digits=0))
write.csv(df_final, "gpinr.csv", row.names =F, quote=F)
